### ISSUE TITLE
Missing documentation for `offered_qos_profiles`

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#1002]
**Description**

The ROS 2 section of MCAP's well-known profiles documentation (https://mcap.dev/spec/registry#ros2) says `offered_qos_profiles` is a required metadata field, but no documentation or example is provided for what this field should contain. Is it JSON-serialized? What are the fields?

EDIT: I found <https://github.com/ros2/rosbag2/issues/609>, it looks like the serialization format is YAML. I'm not sure if there is authoritative documentation that could be linked to, or if all of the fields should be documented on the MCAP site. Even saying "consult the ROS 2 source code for documentation on this field" would be a start.

**Comment by jhurliman** [comment]
Related: https://github.com/ros2/rosbag2/issues/1420

**Comment by defunctzombie** [comment]
@MichaelOrlov @emersonknapp Reading the referenced rosbag issue its not clear to me how to document this or whether the mcap spec is even the correct place to document this.

Options that come to mind:

* Update the spec to say that the field is a string but the string is ROS distro/release specific?
* Remove the documentation of the field from the mcap spec altogether though arguably that makes creating tooling for ROS 2 mcap files harder?
* Be more specific and say that the string is valid yaml? (is it?)

I also noticed that the mcap storage plugin also provides a type hash field now: https://github.com/ros2/rosbag2/blob/rolling/rosbag2_storage_mcap/src/mcap_storage.cpp#L820 which did not exist when we first wrote this profile spec.

**Comment by MichaelOrlov** [comment]
@defunctzombie @jhurliman Can we refer to the section about QoS profile overriding in the Rosbag2 readme file https://github.com/ros2/rosbag2#overriding-qos-profiles and official [How-to Overriding QoS Policies in rosbag2 guide](https://docs.ros.org/en/rolling/How-To-Guides/Overriding-QoS-Policies-For-Recording-And-Playback.html)?

**Comment by jhurliman** [comment]
@MichaelOrlov the only tricky part about those docs is the required format is _slightly_ different. The top-level `/topic_name:` key cannot be present, only the key-values below that. That's what the rosbag2 recorder is writing and expecting to read, anyways. The following "schema" from https://docs.ros.org/en/rolling/How-To-Guides/Overriding-QoS-Policies-For-Recording-And-Playback.html is exactly the documentation that should be provided or linked to, somehow:

```
history: [keep_all, keep_last]
depth: int
reliability: [system_default, reliable, best_effort, unknown]
durability: [system_default, transient_local, volatile, unknown]
deadline:
  sec: int
  nsec: int
lifespan:
  sec: int
  nsec: int
liveliness: [system_default, automatic, manual_by_topic, unknown]
liveliness_lease_duration:
  sec: int
  nsec: int
avoid_ros_namespace_conventions: [true, false]
```
